[build]
  command = "npm run build"
  publish = "dist"

    # This is the key change
  NODE_VERSION = "24" 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/variant-map.json"]